@startuml

actor A1 as "Assistant"

rectangle Database

rectangle "Organisation System" {
    usecase UC2 as "Get all countries
        in the continent, sorted
        by population"

    usecase UCa as "Print / Export
        country list"

    A1 - UC2
    UC2 ..> UCa : include
    UC2 - Database
}

@enduml