@startuml

package "Use Case 30" {

actor A1 as "Planner""

rectangle "Information System" {
    usecase UC30 as "Get population of a district"

     usecase UCa as "Provide //district//"

    usecase UCb as "Print / Export
            country list"

    A1 - UC30
    A1 - UCa
    UCa ..> UC30 : include
    UC30 ..> UCb : include
}
}
@enduml