@startuml

actor A1 as "Planner""

rectangle "Information System" {
    usecase UC4 as "Get top //N// populated
                    countries in the world"

    usecase UCa as "Provide //N//"

    usecase UCb as "Print / Export
            country list"

    A1 - UC4
    A1 - UCa
    UCa ..> UC4 : include
    UC4 ..> UCb : include
}
@enduml