@startuml

actor A1 as "Coordinator"

rectangle "Information System" {
    usecase UC9 as "Get all cities in //region//
                    by population"

    usecase UCa as "Provide //Region//"

    usecase UCb as "Print / Export
            country list"

    A1 - UC9
    A1 - UCa
    UCa ..> UC9 : include
    UC9 ..> UCb : include
}
@enduml